make use of most common content locales
scrapinghub/dateparser pull request #805
Opened 2020-10-07 09:34 UTC by mirceachira

closes #714

2020-10-07 11:34 UTC, Gallaecio approved these changes

2020-10-07 11:35 UTC, Gallaecio commented
Hmm… I don’t see how these changes could cause those CI issues :confused:

2020-10-08 06:48 UTC, noviluni commented
Hi @mirceachira, @Gallaecio 

When running `python order_languages.py` (As @mirceachira  did), we get the order from `https://github.com/unicode-cldr/cldr-dates-full.git`.

Those errors in the pipelines are happening because CLDR included new languages, and when we try to import the languages from the list of languages ( `dateparser.data.language_info.language_order`) we can't find them.

I think the new locales are: ccp, ceb, ff-Latn, ia, jv, ku, mi, sd, tg, tt, wo, xh, yue-Hans and yue-Hant.

To create the files for the new languages we should run:

1. `python get_cldr_data.py` It creates the json files
2. `python write_complete_data.py` It creates the py files.


However, we should also:
* Update the "supported locales" list in the docs
* Update the `avoid_languages` list from `dateparser.dateparser_scripts`. We may need to add some of the new languages or remove some of the old languages from this list.
* Run again the `order_languages` script as it should reflect the `avoid_languages` changes.

@mirceachira would you like to work on this? I think you could create a separate PR just running the three scripts (and updating the docs and the `avoid_languages` list). Once we merge that, we can come here and update this PR and we won't see any issue. 

Of course, if you don't want/ you can't I can do it. :)

2020-10-09 20:28 UTC, mirceachira commented
Hey @noviluni for sure I would like to pick that up! Thanks for the detailed tips on it!

2020-10-29 17:06 UTC, noviluni commented
Hi @mirceachira, you will be able run `python dateparser_scripts/order_languages.py` without errors after merging this: https://github.com/scrapinghub/dateparser/pull/825

However, I checked what you did and I think this is wrong: https://github.com/scrapinghub/dateparser/pull/805/files#diff-1c848ec911779bd8e06fea6e61745c57c43a463bab86d8ef955f2e29ec8484d0R60 because is generating multiple times the same language in the `language_order` list in `languages_info.py`. 

On the other hand, I would really appreciate it if you add the date when that list was created in this comment: https://github.com/scrapinghub/dateparser/pull/805/files#diff-1c848ec911779bd8e06fea6e61745c57c43a463bab86d8ef955f2e29ec8484d0R15 to allow us to update in in the future.

2020-10-30 18:42 UTC, noviluni commented
Hi @mirceachira, we merged the other PR (#825), could you rebase this PR against master? :slightly_smiling_face:

2020-10-31 10:20 UTC, mirceachira commented
@noviluni simply running the script generates the same problem you mentioned here https://github.com/scrapinghub/dateparser/pull/805#issuecomment-705368883

Though there are much fewer tests that required fixing now after #825 . I added the languages accordingly to 'avoid_languages' and fixed the remaining issues. 

Please note that I removed this test: https://github.com/scrapinghub/dateparser/pull/805/commits/11ba3fbf10576b1972b70ba41a6995f87994b4f4
I'm not sure why the locale order resulted in its failure as well as the failure in the shortname test that I fixed here https://github.com/scrapinghub/dateparser/pull/805/commits/876941eb31687602d7d5e5985e37950730524920

2020-11-04 21:14 UTC, Gallaecio commented on dateparser_scripts/order_languages.py
> +}
:lipstick: Can we keep this list alphabetical?

2020-11-04 21:14 UTC, Gallaecio commented on dateparser_scripts/write_complete_data.py
> +from dateparser_scripts.order_languages import avoid_languages
:lipstick: 

```suggestion
from dateparser_scripts.order_languages import avoid_languages
from dateparser_scripts.utils import combine_dicts
```

2020-11-22 18:20 UTC, noviluni requested changes
Hi @mirceachira! 

I think we are almost ready to merge this! I'm ok with the changes in the tests, but I would need you to revert the `avoid_languages` set as suggested and run this: `python dateparser_scripts/order_languages.py` again.

After that I think we will be able to merge it! :rocket:

2020-11-22 18:20 UTC, noviluni commented on dateparser_scripts/order_languages.py
> +}
You wrote here some languages from the next CLDR versions. Could you revert this?

```suggestion
avoid_languages = {'cu', 'kkj', 'nds', 'prg', 'tk', 'vai', 'vai-Latn', 'vai-Vaii', 'vo'}
```

2020-11-25 10:45 UTC, noviluni requested changes

2020-11-25 10:45 UTC, noviluni commented on dateparser_scripts/order_languages.py
> +]
Hi @mirceachira, I rechecked this list before merging and it seems that "Hebrew", "Norwegian Bokmål" and "Norwegian (Nynorsk)" were wrong (those codes you wrote are used in other specifications, but they are not in the `language_order` list). Could you change it? Thanks!

```suggestion
most_common_locales = [
    'en', 'ru', 'es', 'tr', 'fa', 'fr', 'de', 'ja', 'pt', 'vi', 'zh', 'ar', 'it', 'pl', 'in', 'el',
    'nl', 'ko', 'th', 'he', 'uk', 'cs', 'sv', 'ro', 'hu', 'da', 'sr', 'sk', 'fi', 'bg', 'hr', 'lt',
    'hi', 'nb', 'sl', 'nn', 'et', 'lv'
]
```

2020-11-25 10:50 UTC, noviluni commented on dateparser_scripts/order_languages.py
> +]
(I have just seen that you mentioned them as "new" in this comment: https://github.com/scrapinghub/dateparser/issues/714#issuecomment-701373790, but I didn't see that before, sorry)

2020-11-25 11:08 UTC, noviluni commented
I've been opening and closing this PR because we just switched from travis-ci.org to travis-ci.com but the checks show the old travis-ci.org...

Anyway, it seems that all tests passed in travis-ci.com: https://travis-ci.com/github/scrapinghub/dateparser/builds/204189662

2020-11-25 11:21 UTC, noviluni commented
Ok, this is a hard PR to review :sweat_smile: 

You should change the "in" code by "id" in the `most_common_locales` list too, and after that you should run `python dateparser_scripts/write_complete_data.py`.

2020-12-18 15:24 UTC, noviluni commented
Hi @mirceachira, thanks for fixing this. As travis-ci stopped working we can't run the tests, so I can't merge this. I started migrating to `github actions` (WIP PR: https://github.com/scrapinghub/dateparser/pull/859/files) after that we will be able to run the tests and merge this :)

2021-02-09 12:43 UTC, noviluni approved these changes
LGTM!

2021-02-09 12:43 UTC, merged