fix(regex-version): removed version 2021.8.27 that breaks dateparser with SegFault
scrapinghub/dateparser pull request #974
Opened 2021-08-27 18:42 UTC by athossampayo

fix(regex-version): removed version 2021.8.27 that breaks dateparser with SegFault

Related to  #972

Tests result:
![image](https://user-images.githubusercontent.com/67998510/131174617-7558c5c0-2a42-4c9c-b7e5-5fdfe0ff3f25.png)

-----

Fixes: #972. 
Fixes: #973

2021-08-31 18:52 UTC, noviluni requested changes
Hi @athossampayo, thank you for opening this PR. I think the correct way to do it is separating the versions with commas, as set in [PEP-440](https://www.python.org/dev/peps/pep-0440/#version-specifiers): `'regex !=2019.02.19,!=2021.8.27',`

Could you try with these semantics?

Thanks! :)

2021-08-31 19:00 UTC, athossampayo commented
Hello @noviluni, thanks for the tip! Did not find a pattern to follow on this case. 

Already updated the code.

If there's anything more to fix, just say.

Thanks!

2021-09-01 08:38 UTC, noviluni approved these changes
:muscle:

2021-09-01 09:17 UTC, lopuhin approved these changes
Thanks @athossampayo :+1:

2021-09-01 09:17 UTC, merged